/* Bison interface for Yacc-like parsers in C

   Note: This file is auto-generated by Bison. Ensure it matches the
   requirements of your grammar.

*/

#ifndef YY_YY_RECEITA_TAB_H_INCLUDED
# define YY_YY_RECEITA_TAB_H_INCLUDED

/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token type.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    RECEITA = 258,
    LBRACE = 259,
    RBRACE = 260,
    COLON = 261,
    SERVIR = 262,
    ANOTAR = 263,
    MEXERENQUANTO = 264,
    PAREDEMEXER = 265,
    PICARSE = 266,
    SENAO = 267,
    PAREDEPICAR = 268,
    TAMBEM = 269,
    OU = 270,
    EQUAL = 271,
    GREATER = 272,
    LESS = 273,
    G = 274,
    ML = 275,
    NAO = 276,
    MINUS = 277,
    LBRACKET = 278,
    RBRACKET = 279,
    PLUS = 280,
    MULTIPLY = 281,
    DIVIDE = 282,
    IDENTIFIER = 283,
    STRING = 284,
    INTEGER = 285
  };
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
union YYSTYPE
{
#line 10 "receita.y"

    int intval;
    char *strval;

#line 107 "receita.tab.h"

};
typedef union YYSTYPE YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif

extern YYSTYPE yylval;

int yyparse (void);

#endif /* !YY_YY_RECEITA_TAB_H_INCLUDED  */
